#!/bin/bash
# ls | cut  -d "." -f -2
for i in $(ls -d tests/* | grep -v \\.); do
    left=`cat ${i} |./a.out`;
    right=`cat ${i}.a`;
    if test ${left}=${right}; then
        echo ${i} true ${left}  ${right};
    else
        echo ${i} false ${left}  ${right};
    fi
done
